### ISSUE TITLE
"Set layout as default" option only appears once layout is shared

### ISSUE THREAD

**Issue by annaritz** [Murali-group/GraphSpace#202] opened 2016-09-10 23:21 UTC
When you first make a layout, the options are "Delete", "Share", "Edit", and "Link".

![screen shot 2016-09-10 at 4 15 07 pm](https://cloud.githubusercontent.com/assets/1457970/18414074/f9bba308-7771-11e6-863e-3254d947fbd4.png)

When you share the layout, the options become "Unshare","Edit","Link", and "Set as Default".

![screen shot 2016-09-10 at 4 16 06 pm](https://cloud.githubusercontent.com/assets/1457970/18414076/019e299c-7772-11e6-9e3a-97b8fb83794a.png)

I think the buttons should remain consistent regardless of whether the graph is shared or not.  Some can be greyed out, with a hover message (e.g., "Share the layout to set as default") if necessary.

This caused some confusion when students tried to set their layout as the default one.  I'm unsure what label to apply to these kinds of "clarification" issues - please advise if possible.  Thanks!

**Comment by tmmurali** [comment] 2016-09-11 01:12
Duplicate of #171.

**Comment by tmmurali** [comment] 2016-09-11 01:12
@annaritz This issue is a duplicate of #171. Please add comments to #171.

**Closed by tmmurali** 2016-09-11 01:12 UTC
Labels: bio331
