### ISSUE TITLE
Add Step Filter Paths to Default Layouts

### ISSUE THREAD

**Issue by DSin52** [Murali-group/GraphSpace#127] opened 2016-03-07 18:00 UTC
When selecting a default layout for a graph, the layout should also allow for step filters to be part of the layout.  When any user goes to this graph, then the default layout along with the step filter applied when saving the layout should be visible.

**Comment by jlaw9** [comment] 2017-08-18 17:10
Duplicate of #257

**Closed by jlaw9** 2017-08-18 17:10 UTC
Labels: medium priority
